/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HelloWorldResponse,
    HelloWorldResponseFromJSON,
    HelloWorldResponseToJSON,
} from '../models';

export interface HelloRequest {
    name?: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Returns \'Hello\' to the caller
     */
    async helloRaw(requestParameters: HelloRequest): Promise<runtime.ApiResponse<HelloWorldResponse>> {
        const queryParameters: any = {};

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/hello`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => HelloWorldResponseFromJSON(jsonValue));
    }

    /**
     * Returns \'Hello\' to the caller
     */
    async hello(requestParameters: HelloRequest): Promise<HelloWorldResponse> {
        const response = await this.helloRaw(requestParameters);
        return await response.value();
    }

}
